checkIn: SUCCESS
addTable: SUCCESS
checkOut: SUCCESS
checkIn: SUCCESS
checkIn: SUCCESS
checkIn: FAILURE
addTable: SUCCESS
addTable: SUCCESS
addTable: SUCCESS
checkIn: SUCCESS
joinTables: FAILURE
joinTables: FAILURE
checkIn: SUCCESS
addTable: SUCCESS
addTable: SUCCESS
enterDiningRoom: FAILURE
addTable: SUCCESS
leaveDiningRoom: FAILURE
addTable: SUCCESS
joinFriend: FAILURE
checkIn: SUCCESS
