checkIn: SUCCESS
addTable: SUCCESS
checkIn: SUCCESS
leaveDiningRoom: FAILURE
joinFriend: FAILURE
enterDiningRoom: SUCCESS
joinFriend: FAILURE
checkOut: SUCCESS
checkOut: FAILURE
leaveDiningRoom: SUCCESS
joinFriend: FAILURE
checkIn: SUCCESS
addTable: SUCCESS
addTable: SUCCESS
joinFriend: FAILURE
addTable: SUCCESS
reheatFood: SUCCESS
enterDiningRoom: INVALID_INPUT
leaveDiningRoom: FAILURE
joinFriend: FAILURE
checkOut: SUCCESS
cleanNextRoom: SUCCESS, 53
checkIn: SUCCESS
cleanNextRoom: SUCCESS, 100
checkIn: SUCCESS
checkIn: FAILURE
joinTables: SUCCESS
joinFriend: FAILURE
joinTables: SUCCESS
enterDiningRoom: FAILURE
reheatFood: SUCCESS
checkIn: SUCCESS
enterDiningRoom: FAILURE
enterDiningRoom: SUCCESS
addTable: SUCCESS
joinFriend: SUCCESS, 45
checkOut: SUCCESS
enterDiningRoom: SUCCESS
joinFriend: FAILURE
joinFriend: FAILURE
joinTables: FAILURE
joinTables: FAILURE
joinTables: INVALID_INPUT
reheatFood: SUCCESS
checkOut: FAILURE
addTable: SUCCESS
enterDiningRoom: INVALID_INPUT
joinFriend: FAILURE
enterDiningRoom: FAILURE
checkIn: SUCCESS
checkIn: SUCCESS
addTable: SUCCESS
checkIn: SUCCESS
joinFriend: SUCCESS, 45
leaveDiningRoom: FAILURE
joinFriend: SUCCESS, 45
joinTables: SUCCESS
addTable: SUCCESS
removeTable: SUCCESS
joinFriend: INVALID_INPUT
addTable: SUCCESS
removeTable: SUCCESS
enterDiningRoom: FAILURE
enterDiningRoom: FAILURE
cleanNextRoom: SUCCESS, 113
joinTables: FAILURE
addTable: SUCCESS
checkIn: SUCCESS
joinFriend: SUCCESS, 45
checkIn: SUCCESS
enterDiningRoom: SUCCESS
enterDiningRoom: SUCCESS
removeTable: SUCCESS
leaveDiningRoom: FAILURE
checkIn: FAILURE
addTable: SUCCESS
addTable: INVALID_INPUT
enterDiningRoom: FAILURE
checkIn: SUCCESS
checkOut: FAILURE
enterDiningRoom: SUCCESS
enterDiningRoom: FAILURE
addTable: SUCCESS
enterDiningRoom: FAILURE
joinFriend: INVALID_INPUT
reheatFood: SUCCESS
addTable: SUCCESS
joinTables: SUCCESS
cleanNextRoom: SUCCESS, 122
cleanNextRoom: SUCCESS, 148
enterDiningRoom: FAILURE
removeTable: SUCCESS
addTable: SUCCESS
checkIn: FAILURE
checkIn: SUCCESS
checkIn: SUCCESS
removeTable: SUCCESS
checkIn: SUCCESS
enterDiningRoom: FAILURE
checkOut: SUCCESS
addTable: SUCCESS
joinFriend: FAILURE
addTable: SUCCESS
joinFriend: FAILURE
joinTables: SUCCESS
enterDiningRoom: FAILURE
joinFriend: INVALID_INPUT
checkIn: FAILURE
checkIn: SUCCESS
joinTables: FAILURE
checkIn: SUCCESS
enterDiningRoom: FAILURE
checkIn: SUCCESS
joinFriend: FAILURE
removeTable: SUCCESS
removeTable: FAILURE
reheatFood: SUCCESS
enterDiningRoom: FAILURE
cleanNextRoom: SUCCESS, 224
joinTables: FAILURE
checkOut: FAILURE
checkIn: SUCCESS
addTable: INVALID_INPUT
checkIn: INVALID_INPUT
leaveDiningRoom: INVALID_INPUT
checkIn: FAILURE
enterDiningRoom: SUCCESS
leaveDiningRoom: SUCCESS
leaveDiningRoom: FAILURE
checkIn: SUCCESS
joinFriend: FAILURE
addTable: INVALID_INPUT
checkIn: SUCCESS
leaveDiningRoom: FAILURE
removeTable: FAILURE
checkIn: SUCCESS
checkIn: SUCCESS
removeTable: FAILURE
joinFriend: SUCCESS, 25
addTable: SUCCESS
checkOut: SUCCESS
joinFriend: FAILURE
enterDiningRoom: SUCCESS
reheatFood: SUCCESS
cleanNextRoom: SUCCESS, 233
checkIn: SUCCESS
enterDiningRoom: FAILURE
checkIn: SUCCESS
checkIn: SUCCESS
joinTables: FAILURE
checkIn: SUCCESS
enterDiningRoom: SUCCESS
checkOut: SUCCESS
checkIn: FAILURE
checkOut: FAILURE
leaveDiningRoom: FAILURE
leaveDiningRoom: FAILURE
enterDiningRoom: SUCCESS
enterDiningRoom: FAILURE
addTable: SUCCESS
checkIn: SUCCESS
joinFriend: SUCCESS, 45
checkIn: FAILURE
addTable: SUCCESS
leaveDiningRoom: FAILURE
addTable: SUCCESS
checkIn: SUCCESS
enterDiningRoom: SUCCESS
leaveDiningRoom: FAILURE
leaveDiningRoom: FAILURE
checkIn: SUCCESS
reheatFood: SUCCESS
enterDiningRoom: FAILURE
leaveDiningRoom: FAILURE
joinFriend: FAILURE
checkIn: SUCCESS
removeTable: SUCCESS
addTable: SUCCESS
joinTables: FAILURE
removeTable: SUCCESS
addTable: SUCCESS
removeTable: SUCCESS
addTable: SUCCESS
joinFriend: FAILURE
checkIn: SUCCESS
enterDiningRoom: SUCCESS
reheatFood: SUCCESS
enterDiningRoom: SUCCESS
checkIn: FAILURE
checkIn: SUCCESS
leaveDiningRoom: FAILURE
removeTable: SUCCESS
checkIn: SUCCESS
cleanNextRoom: SUCCESS, 234
reheatFood: SUCCESS
addTable: SUCCESS
reheatFood: SUCCESS
checkIn: FAILURE
removeTable: SUCCESS
checkIn: SUCCESS
checkIn: SUCCESS
checkIn: SUCCESS
enterDiningRoom: FAILURE
joinTables: FAILURE
enterDiningRoom: SUCCESS
enterDiningRoom: FAILURE
leaveDiningRoom: FAILURE
cleanNextRoom: SUCCESS, 240
leaveDiningRoom: FAILURE
enterDiningRoom: FAILURE
checkOut: FAILURE
checkOut: SUCCESS
joinTables: SUCCESS
addTable: FAILURE
joinFriend: SUCCESS, 161
joinFriend: SUCCESS, 161
joinFriend: FAILURE
enterDiningRoom: FAILURE
checkIn: SUCCESS
checkIn: SUCCESS
checkIn: SUCCESS
checkIn: SUCCESS
addTable: SUCCESS
joinFriend: SUCCESS, 204
checkIn: SUCCESS
checkIn: SUCCESS
joinFriend: FAILURE
leaveDiningRoom: FAILURE
enterDiningRoom: SUCCESS
cleanNextRoom: SUCCESS, 244
cleanNextRoom: SUCCESS, 249
checkIn: SUCCESS
addTable: SUCCESS
checkIn: FAILURE
checkIn: SUCCESS
enterDiningRoom: FAILURE
enterDiningRoom: SUCCESS
addTable: SUCCESS
addTable: SUCCESS
checkOut: SUCCESS
checkOut: SUCCESS
enterDiningRoom: SUCCESS
joinFriend: SUCCESS, 132
checkOut: SUCCESS
joinTables: SUCCESS
checkIn: SUCCESS
checkIn: SUCCESS
enterDiningRoom: SUCCESS
checkOut: SUCCESS
checkIn: FAILURE
